retry
VinITAAcademy/b23_dv_dark2 pull request #11
Opened 2024-01-15 19:52 UTC by Roman1518

2024-01-15 21:15 UTC, VladislavLiubasiuk approved these changes

2024-01-16 13:03 UTC, VitaliyBogdanuk requested changes

2024-01-16 13:03 UTC, VitaliyBogdanuk commented on src/css/style.css
> +    width: 768px;
відступи

2024-01-16 13:03 UTC, VitaliyBogdanuk commented on src/css/style.css
> +    width: 50px;
відступи

2024-01-16 13:03 UTC, VitaliyBogdanuk commented on src/js/script.js
> +let swiper2 = new Swiper(".logo-swiper", {
Я в субботу казав переписати ініціалізацію слайдерів з використанням 'id' а не класів.

2024-01-16 13:03 UTC, VitaliyBogdanuk commented on src/js/script.js
> +const swiper = new Swiper('.swiper_lp', {
Я в субботу казав переписати ініціалізацію слайдерів з використанням 'id' а не класів.

2024-01-18 10:24 UTC, Roman1518 commented on src/css/style.css
> +    width: 768px;
виправив

2024-01-18 10:24 UTC, Roman1518 commented on src/css/style.css
> +    width: 50px;
виправив

2024-01-18 10:24 UTC, Roman1518 commented on src/js/script.js
> +let swiper2 = new Swiper(".logo-swiper", {
виправив

2024-01-18 10:24 UTC, Roman1518 commented on src/js/script.js
> +const swiper = new Swiper('.swiper_lp', {
виправив

2024-01-18 15:46 UTC, merged