ADD_All_Forms_end_SuccessfulRequest_Modal_Windows
VinITAAcademy/b23_dv_dark2 pull request #35
Opened 2024-01-27 10:10 UTC by ShlenchakBogdan

ADD_All_Forms_end_SuccessfulRequest_Modal_Windows

2024-01-27 10:14 UTC, VladislavLiubasiuk commented on src/Img/modal-selection-cancel.png
we have this icon made in icomoon

2024-01-27 10:15 UTC, Roman1518 approved these changes

2024-01-27 10:15 UTC, VladislavLiubasiuk commented on src/css/style.css
> +    }
I believe this can be shortened a bit

2024-01-27 10:18 UTC, VladislavLiubasiuk requested changes
redundant cancel, should be used through icomoon
minor issues in css, dublicating code

2024-01-29 18:23 UTC, VitaliyBogdanuk commented
@ShlenchakBogdan conflict

2024-02-01 15:38 UTC, closed without merging